<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shubbak.Core\Shubbak.Core.csproj" />
    <ProjectReference Include="..\Shubbak.Ipc\Shubbak.Ipc.csproj" />
    <ProjectReference Include="..\Shubbak.Config\Shubbak.Config.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
